Controllers/MajorsController.cs
using StudentRegSys.Dtos;
using StudentRegSys.Models;
using StudentRegSys.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace StudentRegSys.Controllers
{
    public class MajorsController : Controller
    {
        private ApplicationDbContext _context;
        public MajorsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Majors/MajorsManagement
        public ActionResult MajorsManagement()
        {
            try
            {
                var majors = _context.Major.ToList();

                return View(majors);
            }
            catch (Exception)
            {
                return HttpNotFound();
            }
        }

        // GET: Majors/MajorForm
        public ActionResult MajorForm()
        {
            try
            {
                var major = new Major();

                major.IsAdd = true;

                return View(major);
            }
            catch (Exception)
            {
                return HttpNotFound();
            }
        }

        //GET: Majors/Edit/1
        public ActionResult Edit(int id)
        {
            try
            {
                var major = _context.Major.SingleOrDefault(m => m.ID == id);

                if (major == null)
                    return HttpNotFound();

                major.IsAdd = false;
                return View("MajorForm", major);
            }
            catch (Exception)
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Major major)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View("MajorForm", major);

                // Add
                if (major.ID == 0)
                {
                    if (_context.Major.Any(m => m.Name == major.Name))
                    {
                        ModelState.AddModelError("Name", "This Major Name is already exists");
                        major.IsAdd = true;
                        return View("MajorForm", major);
                    }
                    _context.Major.Add(major);
                }
                // Edit
                else
                {
                    if (_context.Major.Any(m => m.Name == major.Name && m.ID != major.ID))
                    {
                        ModelState.AddModelError("Name", "This Major Name is already exists");
                        major.IsAdd = false;
                        return View("MajorForm", major);
                    }

                    var majorInDb = _context.Major.Single(m => m.ID == major.ID);
                    majorInDb.Name = major.Name;
                }
                _context.SaveChanges();
                return RedirectToAction("MajorsManagement");
            }
            catch (Exception)
            {
                return View("MajorForm", major);
            }
        }

        //Save method using web Api
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveApi(MajorDto majorDto)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:63349/api/");

                    //HTTP POST
                    if (majorDto.ID == 0)
                    {
                        var postTask = client.PostAsJsonAsync<MajorDto>("majors", majorDto);
                        postTask.Wait();

                        var result = postTask.Result;
                        if (!result.IsSuccessStatusCode)
                        {
                            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

                            return RedirectToAction("MajorForm", majorDto);
                        }
                    }
                    //HTTP PUT
                    else
                    {
                        var putTask = client.PutAsJsonAsync<MajorDto>("majors/" + majorDto.ID.ToString(), majorDto);
                        putTask.Wait();

                        var result = putTask.Result;
                        if (!result.IsSuccessStatusCode)
                        {
                            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

                            return RedirectToAction("MajorForm", majorDto);
                        }
                    }

                    return RedirectToAction("MajorsManagement");
                }
            }
            catch (Exception)
            {
                return RedirectToAction("MajorForm", majorDto);
            }
        }

        // DELETE: Students/Delete/1
        public ActionResult Delete(int id)
        {
            try
            {
                var major = _context.Major.SingleOrDefault(m => m.ID == id);

                if (!(major == null))
                {
                    _context.Major.Remove(major);
                }
                _context.SaveChanges();
                return RedirectToAction("MajorsManagement");
            }
            catch (Exception)
            {
                return RedirectToAction("MajorsManagement");
            }
        }

    }
}

Controllers/StudentsController.cs
using StudentRegSys.Dtos;
using StudentRegSys.Models;
using StudentRegSys.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace StudentRegSys.Controllers
{
    public class StudentsController : Controller
    {
        private ApplicationDbContext _context;
        public StudentsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Students/StudentsManagement
        public ActionResult StudentsManagement()
        {
            try
            {
                var students = _context.Student.ToList();

                return View(students);
            }
            catch (Exception)
            {
                return HttpNotFound();
            }
        }

        // GET: Students/StudentForm
        public ActionResult StudentForm()
        {
            try
            {
                var student = new Student();

                var majors = _context.Major.ToList();
                var viewModel = new StudentViewModel
                {
                    Student = student,
                    Majors = majors
                };

                viewModel.IsAdd = true;

                return View(viewModel);
            }
            catch (Exception)
            {
                return HttpNotFound();
            }
        }

        //GET: Students/Edit/1
        public ActionResult Edit(int id)
        {
            try
            {
                var student = _context.Student.SingleOrDefault(s => s.ID == id);

                if (student == null)
                    return HttpNotFound();

                var majors = _context.Major.ToList();
                var viewModel = new StudentViewModel
                {
                    Student = student,
                    Majors = majors
                };

                viewModel.IsAdd = false;
                return View("StudentForm", viewModel);
            }
            catch (Exception)
            {
                return HttpNotFound();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Student student)
        {
            try
            {
                var majors = _context.Major.ToList();
                var viewModel = new StudentViewModel
                {
                    Student = student,
                    Majors = majors
                };

                if (!ModelState.IsValid)
                    return View("StudentForm", viewModel);

                // To get the path and generate Name for the new uploded image
                HttpPostedFileBase file = null;
                var path = "";


                if (Request.Files.Count > 0)
                {
                    file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileExtension = Path.GetExtension(file.FileName);
                        var fileName = "StudentPic_" + student.Name + fileExtension;
                        path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                        student.Photo = "/Images/" + fileName;
                    }
                }

                // Add
                if (student.ID == 0)
                {
                    if (_context.Student.Any(s => s.Name == student.Name))
                    {
                        ModelState.AddModelError("Student.Name", "This Student Name is already exists");
                        viewModel.IsAdd = true;
                        return View("StudentForm", viewModel);
                    }
                    _context.Student.Add(student);
                }
                // Edit
                else
                {
                    if (_context.Student.Any(s => s.Name == student.Name && s.ID != student.ID))
                    {
                        ModelState.AddModelError("Student.Name", "This Student Name is already exists");
                        viewModel.IsAdd = false;
                        return View("StudentForm", viewModel);
                    }

                    var studentInDb = _context.Student.Single(s => s.ID == student.ID);

                    string old_path = Server.MapPath(studentInDb.Photo);
                    FileInfo fi = new FileInfo(old_path);
                    if (fi.Exists)
                        fi.Delete();

                    studentInDb.Name = student.Name;
                    studentInDb.DateofBirth = student.DateofBirth;
                    studentInDb.Gender = student.Gender;
                    studentInDb.Address = student.Address;
                    studentInDb.Phone = student.Phone;
                    studentInDb.Photo = student.Photo;
                    studentInDb.MajorID = student.MajorID;
                }

                if (path != "")
                    // to crop and save the uploaded pic
                    /* for automatically crop the image in largest 1:1 ratio (sequre) possible enter 0's in
                    the maxWidth & maxHeight parametesrs */
                    SaveCroppedImage(Image.FromStream(file.InputStream), 0, 0, path); 

                _context.SaveChanges();
                return RedirectToAction("StudentsManagement");
            }
            catch (Exception)
            {
                return View("StudentForm", student);
            }
        }

        // DELETE: Students/Delete/1
        public ActionResult Delete(int id)
        {
            try
            {
                var student = _context.Student.SingleOrDefault(s => s.ID == id);

                if (!(student == null))
                {
                    _context.Student.Remove(student);

                    // to delete saved image
                    string path = Server.MapPath(student.Photo);
                    FileInfo fi = new FileInfo(path);
                    if (fi.Exists)
                        fi.Delete();
                }
                _context.SaveChanges();
                return RedirectToAction("StudentsManagement");
            }
            catch (Exception)
            {
                return RedirectToAction("StudentsManagement");
            }
        }

        //Helper method
        public bool SaveCroppedImage(Image image, int maxWidth, int maxHeight, string filePath)
        {
            ImageCodecInfo jpgInfo = ImageCodecInfo.GetImageEncoders()
                                     .Where(codecInfo =>
                                     codecInfo.MimeType == "image/jpeg").First();
            Image finalImage = image;

            //to encodes the rotation/flipping necessary to display the image correctly
            //PropertyItem pi = image.PropertyItems.Select(x => x)
            //       .FirstOrDefault(x => x.Id == 0x0112);


            //byte o = pi.Value[0];

            //if (o == 2) image.RotateFlip(RotateFlipType.RotateNoneFlipX);
            //if (o == 3) image.RotateFlip(RotateFlipType.RotateNoneFlipXY);
            //if (o == 4) image.RotateFlip(RotateFlipType.RotateNoneFlipY);
            //if (o == 5) image.RotateFlip(RotateFlipType.Rotate90FlipX);
            //if (o == 6) image.RotateFlip(RotateFlipType.Rotate90FlipNone);
            //if (o == 7) image.RotateFlip(RotateFlipType.Rotate90FlipY);
            //if (o == 8) image.RotateFlip(RotateFlipType.Rotate90FlipXY);

            System.Drawing.Bitmap bitmap = null;
            try
            {
                //to automatically take the largest sequre dimensions possible 
                if (maxWidth == 0 && maxHeight == 0)
                {
                    if (image.Width > image.Height)
                    {
                        maxWidth = image.Width;
                        maxHeight = image.Width;
                    }
                    else
                    {
                        maxWidth = image.Height;
                        maxHeight = image.Height;
                    }
                }

                int left = 0;
                int top = 0;
                int srcWidth = maxWidth;
                int srcHeight = maxHeight;
                bitmap = new System.Drawing.Bitmap(maxWidth, maxHeight);
                double croppedHeightToWidth = (double)maxHeight / maxWidth;
                double croppedWidthToHeight = (double)maxWidth / maxHeight;

                if (image.Width > image.Height)
                {
                    srcWidth = (int)(Math.Round(image.Height * croppedWidthToHeight));
                    if (srcWidth < image.Width)
                    {
                        srcHeight = image.Height;
                        left = (image.Width - srcWidth) / 2;
                    }
                    else
                    {
                        srcHeight = (int)Math.Round(image.Height * ((double)image.Width / srcWidth));
                        srcWidth = image.Width;
                        top = (image.Height - srcHeight) / 2;
                    }
                }
                else
                {
                    srcHeight = (int)(Math.Round(image.Width * croppedHeightToWidth));
                    if (srcHeight < image.Height)
                    {
                        srcWidth = image.Width;
                        top = (image.Height - srcHeight) / 2;
                    }
                    else
                    {
                        srcWidth = (int)Math.Round(image.Width * ((double)image.Height / srcHeight));
                        srcHeight = image.Height;
                        left = (image.Width - srcWidth) / 2;
                    }
                }
                using (Graphics g = Graphics.FromImage(bitmap))
                {
                    g.SmoothingMode = SmoothingMode.HighQuality;

Views/Shared/_CustomLayout.cshtml
@{
    string HomeActive = ViewBag.title == "Home" ? "active" : string.Empty;
    string AboutActive = ViewBag.title == "About us" ? "active" : string.Empty;
    string ContactActive = ViewBag.title == "Contact" ? "active" : string.Empty;
    string AdminActive =
        ViewBag.title == "Students Management" ||
        ViewBag.title == "Majors Management" ||
        ViewBag.title == "New Student" ||
        ViewBag.title == "New Major" ||
        ViewBag.title == "Edit Student" ||
        ViewBag.title == "Edit Major" ? "active" : string.Empty;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    @if (ViewBag.title == "Home")
    {
        <title>Student Registration System</title>
    }
    else
    {
        <title>@ViewBag.Title - Student Registration System</title>
    }
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,700" rel="stylesheet">
    @Styles.Render("~/template/css")


    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="~/Content/ico/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="~/Content/ico/apple-touch-icon.png" />
    <link rel="apple-touch-icon" sizes="57x57" href="~/Content/ico/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="~/Content/ico/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Content/ico/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="~/Content/ico/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="~/Content/ico/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="~/Content/ico/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="~/Content/ico/apple-touch-icon-152x152.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/ico/apple-touch-icon-180x180.png" />

</head>

<body>
    <header>
        <!-- Navbar
        ================================================== -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <!-- logo -->
                    <a class="brand logo" href="@Url.Action("Index","Home")"><img class="logo" src="~/Content/img/srs-logo.png" alt=""></a>
                    <!-- end logo -->
                    <!-- top menu -->
                    <div class="navigation">
                        <nav>
                            <ul class="nav topnav">
                                <li class="dropdown @HomeActive">
                                    <a class="main" href="@Url.Action("Index","Home")">Home</a>
                                </li>
                                <li class="dropdown @AboutActive">
                                    <a class="main" href="@Url.Action("About","Home")">About</a>
                                </li>
                                <li class="dropdown @AdminActive">
                                    <a class="main" href="#">Admin Area</a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown">
                                            <a href="@Url.Action("StudentsManagement","Students")">Students Management</a>
                                            <ul class="dropdown-menu sub-menu">
                                                <li><a href="@Url.Action("StudentForm","Students")">New Student</a></li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="@Url.Action("MajorsManagement","Majors")">Majors Management</a>
                                            <ul class="dropdown-menu sub-menu">
                                                <li><a href="@Url.Action("MajorForm","Majors")">New Major</a></li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#">Errors Test</a>
                                            <ul class="dropdown-menu sub-menu">
                                                <li><a href="@Url.Action("Error","Home")">Exception</a></li>
                                                <li><a href="~/404.html">404</a></li>
                                                <li><a href="~/500.html">500</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="@ContactActive">
                                    <a class="main" href="@Url.Action("Contact","Home")">Contact</a>
                                </li>
                            </ul>
                            <select><option selected="selected" value="">Go to...</option><option value="/">Home</option><option value="/Home/About">About</option><option value="#">Admin Area</option><option value="/Students/StudentsManagement">Students Management</option><option value="/Students/StudentForm">New Student</option><option value="/Majors/MajorsManagement">Majors Management</option><option value="/Majors/MajorForm">New Major</option><option value="#">Errors Test</option><option value="/Home/Error">Exception</option><option value="/404.html">404</option><option value="/500.html">500</option><option value="/Home/Contact">Contact</option></select>
                        </nav>
                    </div>
                    <!-- end menu -->
                </div>
            </div>
        </div>
    </header>

    @RenderBody()

    <!-- Footer
    ================================================== -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <div class="widget">
                        <h5>Browse pages</h5>
                        <ul class="regular">
                            <li><a href="@Url.Action("Contact", "Home")">Work for us</a></li>
                            <li><a href="#">Home page</a></li>
                            <li><a href="#maincontent">Registered students</a></li>
                            <li><a href="404.html">404 Page not found</a></li>
                            <li><a href="@Url.Action("About", "Home")">Meet the team</a></li>
                        </ul>
                    </div>
                </div>
                <div class="span4">
                    <div class="widget">
                        <h5>Admin pages</h5>
                        <ul class="regular">
                            <li><a href="@Url.Action("StudentsManagement","Students")">Students Management</a></li>
                            <li><a href="@Url.Action("StudentForm","Students")">New Student</a></li>
                            <li><a href="@Url.Action("MajorsManagement","Majors")">Majors Management</a></li>
                            <li><a href="@Url.Action("MajorForm","Majors")">New Major</a></li>
                        </ul>
                    </div>
                </div>
                <div class="span4">
                    <div class="widget">
                        <!-- logo -->
                        <a class="brand logo" href="@Url.Action("Index","Home")">
                            <img class="logo" src="~/Content/img/srs-logo.png" alt="">
                        </a>
                        <!-- end logo -->
                        <address>
                            <strong>Student Registration System, Inc.</strong><br>
                            Ibn Abi Bakrah Street<br />
                            Shafabadran, Amman, Jordan<br />
                            <abbr title="Phone">P:</abbr> (962) 79-9818447
                        </address>
                    </div>
                </div>
            </div>
        </div>
        <div class="verybottom">
            <div class="container">
                <div class="row">
                    <div class="span6">
                        <p>
                            &copy; @DateTime.Now.Year Student Registration System. All rights reserved.
                        </p>
                    </div>
                    <div class="span6">
                        <div class="credits">
                            Designed by <a href="@Url.Action("About", "Home")">Mousa Al-Kalouti</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <a id="scrollupbutton"></a>

    @Scripts.Render("~/template/js")
    @RenderSection("scripts", required: false)

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>